### ISSUE TITLE
Jak opiekun chcę mieć możliwość edycji nagrody.

### ISSUE THREAD

**Issue by tgbdc7** [zetonteam/zeton_django#103]

**Comment by tgbdc7** [comment]
ednpoint `PATCH /api/students/<id:int>/prizes/<prize_id:int> `

**Comment by tgbdc7** [comment]
czy chcemy żeby było Id studenta w tej ścieżce.

**Comment by arkjedrz** [comment]
This is done. PATCH "students/int:student_id/prize/int:prize_id".
