### ISSUE TITLE
Discussion on subject of urls structure

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_django#111]

**Comment by pyexplorerhs3** [comment]
??Subject Discussion??
Pure REST endpoints without request.post or combine with both (Proposition from https://github.com/zetonteam/zeton_django/pull/110)

**Comment by MateuszBelczowski** [comment]
There was a discussion about how to structure URLs for nested resources (e.g. tasks).

In my opinion we should stick to the convention with having both IDs (student ID and task ID) explicitly in the URL (`/api/students/<student_id>/tasks/<task_id>`). An example would be `/api/students/1/tasks/2`

- it's pretty standard convention in the REST API world that ID following the resource name is identifying that resource - so in the example above `1` identifies the student and `2` identifies the task
- we could potentially implement HTTP PATCH using endpoint like `api/students/1/tasks` and enforce client to pass `task_id` in the body payload
- as far as I know, it's not that common to use HTTP DELETE with a body, so when implementing deletion of a task, we should perhaps stick to two IDs in the URL anyway

**Comment by arkjedrz** [comment]
I'm not sure what the reason behind some end-points ending in '/' and some not?
