### ISSUE TITLE
Endpoints tracking

### ISSUE THREAD

**Issue by arkjedrz** [zetonteam/zeton_django#120]
Should endpoints be defined and tracked in `README.md`?

If yes, I propose following table:

| op. | URL | impl | tests |
| --- | --- | --- | --- |
| GET | /api/students | ✅ | ❌ |
| POST | /api/students | ❌ | ❌ | 

If no, I'll remove it.

**Comment by tgbdc7** [comment]
Yes, we want endpoints to be defined and tracked in the README.md, and your proposal looks pretty. We like pretty things.
