### ISSUE TITLE
Fix README for "students/int:student_id/task/int:task_id/" GET

### ISSUE THREAD

**Issue by arkjedrz** [zetonteam/zeton_django#199]
It's implemented but marked as not.

**Comment by miniMax18** [comment]
Because this did in #135

**Comment by miniMax18** [comment]
I have closed that issue after edited name of #135 into subject like above here(from /int:id/ to /int:task_id/). Mission completed 💯 👍

**Comment by arkjedrz** [comment]
This is not the endpoint I'm referring to.
