### ISSUE TITLE
Number of total student points shouldn't be allowed to go below 0

### ISSUE THREAD

**Issue by MartaSien** [zetonteam/zeton_django#201]
If not, should we check it in front end or backend?

For now, it is allowed: 
![image](https://github.com/user-attachments/assets/c00fed85-93b7-4c37-9845-9aab727d9014)

**Comment by arkjedrz** [comment]
Discussed today (25.09.2024).
Server should respond with status code 400 and explanation why such case is disallowed.
This scenario should still be checked on frontend side (so in the end it should be rare to happen).
