### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by MartaSien** [zetonteam/zeton_django#82]
There may be unused code within the repository - it should be verified and, if necessary, removed.

- [x] Try out https://pypi.org/project/vulture/
- [x] Try to create a Django-oriented configuration for Vulture and test it again

**Comment by szmktk** [comment]
I'll just run https://pypi.org/project/vulture/ and see what happens

EDIT: nah, it does not recognize variables & fields used by Django :face_with_diagonal_mouth:

**Comment by MartaSien** [comment]
But a good idea to use an automated solution. Perhaps there is one that works for our case. 🙂

According to [this article](https://adamj.eu/tech/2023/07/12/django-clean-up-unused-code-vulture/), there is a way to configure Vulture better for Django projects, by excluding certain decorators and files.

**Comment by pyexplorerhs3** [comment]
```
❯ vulture . | grep 100\%
tests/conftest.py:6: unused variable 'django_db_setup' (100% confidence, 1 line)
users/views.py:40: unused variable 'format' (100% confidence, 1 line)
users/views.py:180: unused variable 'format' (100% confidence, 1 line)
```
