### ISSUE TITLE
Podbić paczki.

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_django#85]
Jesteśmy super

**Comment by pyexplorerhs3** [comment]
yeah

**Comment by szmktk** [comment]
Useful tool: https://pypi.org/project/pip-upgrader/

**Comment by szmktk** [comment]
Actually this one is already covered in https://github.com/zetonteam/zeton_django/issues/91 & https://github.com/zetonteam/zeton_django/pull/102
