### ISSUE TITLE
Jako opiekun chcę dodawać zadania podopiecznemu

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_django#86]
POST | students/int:id/tasks

Check if backend is done

**Comment by pyexplorerhs3** [comment]
removed `TaskSerializer.student_id` field and fill it with student id from URL instead, as described here:
https://www.django-rest-framework.org/api-guide/serializers/#passing-additional-attributes-to-save

**Comment by tgbdc7** [comment]
backend is done.

**Comment by adrian13508** [comment]
Case should be redesigned. Tasks are reusable by design, so there should be some flag added to monitor states 'to do', 'in progress', 'done', 'rejected' or something similar.

**Comment by MartaSien** [comment]
POST | students/int:id/tasks

**Comment by arkjedrz** [comment]
This is done. POST "students/int:student_id/tasks".
