### ISSUE TITLE
dodać pre-commit z ruffem

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_django#93]
❗ spory pull request wyjdzie jak `ruff` sformatuje wszystko na raz

@szmktk no dobra ale co z tym jest?

**Comment by szmktk** [comment]
> ❗ spory pull request wyjdzie jak ruff sformatuje wszystko na raz

@pyexplorerhs3 masz na myśli [ten PR](https://github.com/zetonteam/zeton_django/pull/67)?
Nie był aż taki duży 😛 
Uruchomiłem komendę `pre-commit install` na kompie `bandzior` - pre-commit powinien formatować kod automatycznie.

**Comment by pyexplorerhs3** [comment]
u mnie działa 👍
