### ISSUE TITLE
Pobieranie historii punktów (GET)

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_django#94]
GET | students/int:id/points

Jako opiekun chcę zobaczyć historię zdarzeń na punktach podopiecznego. 
przykład:

Kuba dostał 50 punktów za sprzątnięcie pokoju. 
Kuba wymienił 10 punktów na minutokomputer

**Comment by tgbdc7** [comment]
Przetestuj proszę. 

Ewentualnie dodaj dokumentację

**Comment by MartaSien** [comment]
GET | students/int:id/points

**Comment by arkjedrz** [comment]
This is done. GET "students/int:student_id/points".
